Add "--label" arg on startup
vedro-universe/vedro-allure-reporter pull request #9
Opened 2023-05-09 07:17 UTC by artkuznetsov

2023-06-23 15:16 UTC, artkuznetsov commented on vedro_allure_reporter/_allure_reporter.py
> +        group = event.arg_parser.add_argument_group("Allure Reporter")
смущает, что тут добавляю группу еще одну, что делаю и в другом методе

2023-06-24 07:42 UTC, tsv1 requested changes

2023-06-24 07:42 UTC, tsv1 commented on vedro_allure_reporter/_allure_reporter.py
> +    allure_labels: [List[str]] = []
I believe it would be prudent to only allow the use of the --allure-labels option through the command line.

2023-06-24 07:42 UTC, tsv1 commented on vedro_allure_reporter/_allure_reporter.py
> +                           nargs="*",
I believe it would be better to require at least one label as mandatory (`nargs="+"`)

2023-06-24 07:42 UTC, tsv1 commented on vedro_allure_reporter/_allure_reporter.py
> +            label = (name, value)
I think it would be beneficial to make the key case-insensitive

2023-06-24 07:42 UTC, tsv1 commented on vedro_allure_reporter/_allure_reporter.py
> +            if labels.isdisjoint(scenario_labels):
I was expecting that specifying multiple labels would be interpreted as an AND condition, not an OR.

2023-06-24 07:42 UTC, tsv1 commented on vedro_allure_reporter/_allure_reporter.py
> +                           default=[],
The default value should be None, otherwise the None check in the on_startup function won't be executed, and no tests will run.

2023-06-24 07:53 UTC, tsv1 commented on tests/test_allure_reporter_integration.py
> +        assert reporter._allure_labels == labels
It's generally recommended to refrain from utilizing private methods within test cases, as it's not typically seen as good practice

2023-06-24 10:09 UTC, tsv1 approved these changes
LGTM

2023-06-24 10:09 UTC, merged